-- MySQL Script generated by MySQL Workbench
-- sáb 25 nov 2023 22:48:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Classificacao` (
  `idClassificacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClassificacao`),
  UNIQUE INDEX `idClassificação_UNIQUE` (`idClassificacao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subclassifacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subclassifacao` (
  `idSubclassifacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `Classificacao_idClassificacao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSubclassifacao`),
  UNIQUE INDEX `idSubclassifação_UNIQUE` (`idSubclassifacao` ASC) VISIBLE,
  INDEX `fk_Subclassifação_Classificação1_idx` (`Classificacao_idClassificacao` ASC) VISIBLE,
  CONSTRAINT `fk_Subclassifação_Classificação1`
    FOREIGN KEY (`Classificacao_idClassificacao`)
    REFERENCES `mydb`.`Classificacao` (`idClassificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `Estado_idEstado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC) VISIBLE,
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(14) NOT NULL,
  `NOME_FANTASIA` VARCHAR(100) NOT NULL,
  `RAZAO_SOCIAL` VARCHAR(100) NOT NULL,
  `INSCRICAO_ESTADUAL` VARCHAR(30) NOT NULL,
  `ENDERECO` VARCHAR(100) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `TELEFONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `Cidade_idCidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `idFornecedor_UNIQUE` (`idFornecedor` ASC) VISIBLE,
  UNIQUE INDEX `RAZÃO SOCIAL_UNIQUE` (`RAZAO_SOCIAL` ASC) VISIBLE,
  UNIQUE INDEX `INSCRIÇÃO ESTADUAL_UNIQUE` (`INSCRICAO_ESTADUAL` ASC) VISIBLE,
  INDEX `fk_Fornecedor_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fabricante` (
  `idFabricante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME_FANTASIA` VARCHAR(100) NOT NULL,
  `RAZAO_SOCIAL` VARCHAR(100) NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idFabricante`),
  UNIQUE INDEX `idFabricante_UNIQUE` (`idFabricante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  `Subclassifacao_idSubclassifacao` INT UNSIGNED NOT NULL,
  `Fornecedor_idFornecedor` INT UNSIGNED NOT NULL,
  `Fabricante_idFabricante` INT UNSIGNED NOT NULL,
  `Quantidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Produto_Subclassifação1_idx` (`Subclassifacao_idSubclassifacao` ASC) VISIBLE,
  INDEX `fk_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Produto_Fabricante1_idx` (`Fabricante_idFabricante` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Subclassifação1`
    FOREIGN KEY (`Subclassifacao_idSubclassifacao`)
    REFERENCES `mydb`.`Subclassifacao` (`idSubclassifacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Fabricante1`
    FOREIGN KEY (`Fabricante_idFabricante`)
    REFERENCES `mydb`.`Fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(100) NOT NULL,
  `SENHA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuário_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC) VISIBLE,
  UNIQUE INDEX `SENHA_UNIQUE` (`SENHA` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `RG` VARCHAR(10) NOT NULL,
  `ENDERECO` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `BAIRRO` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(100) NULL,
  `Usuario_idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idFuncionário_UNIQUE` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `CPF DO FUNCIONÁRIO_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `RG DO FUNCIONÁRIO_UNIQUE` (`RG` ASC) VISIBLE,
  INDEX `fk_Pessoa_Usuário1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Usuário1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CRF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CRF` (
  `NUMERO_CRF` VARCHAR(20) NOT NULL,
  `DATA_EXPEDICAO` DATE NOT NULL,
  `DATA_VENCIMENTO` DATE NOT NULL,
  `NUMERO_DIPLOMA` VARCHAR(45) NOT NULL,
  `INSTITUICAO_FORMACAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NUMERO_CRF`),
  UNIQUE INDEX `NÚMERO DO CRF_UNIQUE` (`NUMERO_CRF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Pessoa_idPessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CONVENIO` VARCHAR(30) NULL,
  `SCORE` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  INDEX `fk_Cliente_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `Pessoa_idFuncionário_UNIQUE` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscal` (
  `IDNOTAFISCAL` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `VALOR_TOTAL` DOUBLE NOT NULL,
  `DATA_EMISSAO` DATE NOT NULL,
  PRIMARY KEY (`IDNOTAFISCAL`),
  UNIQUE INDEX `idNota Fiscal_UNIQUE` (`IDNOTAFISCAL` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscalEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscalEntrada` (
  `NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  `Fornecedor_idFornecedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`NotaFiscal_IDNOTAFISCAL`),
  INDEX `fk_Nota Fiscal de Entrada_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Nota Fiscal de Entrada_Nota Fiscal1`
    FOREIGN KEY (`NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscal` (`IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota Fiscal de Entrada_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Pessoa_idPessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CRF_NUMERO_CRF` VARCHAR(20) NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  INDEX `fk_Funcionario_Pessoa_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Funcionario_CRF1_idx` (`CRF_NUMERO_CRF` ASC) VISIBLE,
  UNIQUE INDEX `Pessoa_idFuncionário_UNIQUE` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_CRF1`
    FOREIGN KEY (`CRF_NUMERO_CRF`)
    REFERENCES `mydb`.`CRF` (`NUMERO_CRF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscalSaida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscalSaida` (
  `NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  `Cliente_Pessoa_idCliente` INT UNSIGNED NULL,
  `Funcionario_Pessoa_idFuncionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`NotaFiscal_IDNOTAFISCAL`),
  INDEX `fk_Nota Fiscal de Saída_Cliente1_idx` (`Cliente_Pessoa_idCliente` ASC) VISIBLE,
  INDEX `fk_Nota Fiscal de Saída_Funcionario1_idx` (`Funcionario_Pessoa_idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_Nota Fiscal de Saída_Nota Fiscal1`
    FOREIGN KEY (`NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscal` (`IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota Fiscal de Saída_Cliente1`
    FOREIGN KEY (`Cliente_Pessoa_idCliente`)
    REFERENCES `mydb`.`Cliente` (`Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota Fiscal de Saída_Funcionario1`
    FOREIGN KEY (`Funcionario_Pessoa_idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReceitaMedica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReceitaMedica` (
  `idReceitaMedica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CRM_MEDICO` VARCHAR(30) NOT NULL,
  `NOME_HOSPITAL` VARCHAR(100) NOT NULL,
  `DATA_EMISSAO` DATE NOT NULL,
  `VALIDADE` DATE NOT NULL,
  `NOME_MEDICO` VARCHAR(45) NOT NULL,
  `NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idReceitaMedica`),
  UNIQUE INDEX `idReceita Médica_UNIQUE` (`idReceitaMedica` ASC) VISIBLE,
  INDEX `fk_Receita Médica_Nota Fiscal de Saída1_idx` (`NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL` ASC) VISIBLE,
  CONSTRAINT `fk_Receita Médica_Nota Fiscal de Saída1`
    FOREIGN KEY (`NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscalSaida` (`NotaFiscal_IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPagamento` (
  `idTipoPagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoPagamento`),
  UNIQUE INDEX `idTipos de Pagamentos_UNIQUE` (`idTipoPagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscal_has_TipoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscal_has_TipoPagamento` (
  `NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  `TipoPagamento_idTipoPagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`NotaFiscal_IDNOTAFISCAL`, `TipoPagamento_idTipoPagamento`),
  INDEX `fk_Nota Fiscal_has_Tipo de Pagamentos_Tipo de Pagamentos1_idx` (`TipoPagamento_idTipoPagamento` ASC) VISIBLE,
  INDEX `fk_Nota Fiscal_has_Tipo de Pagamentos_Nota Fiscal1_idx` (`NotaFiscal_IDNOTAFISCAL` ASC) VISIBLE,
  CONSTRAINT `fk_Nota Fiscal_has_Tipo de Pagamentos_Nota Fiscal1`
    FOREIGN KEY (`NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscal` (`IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota Fiscal_has_Tipo de Pagamentos_Tipo de Pagamentos1`
    FOREIGN KEY (`TipoPagamento_idTipoPagamento`)
    REFERENCES `mydb`.`TipoPagamento` (`idTipoPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscalSaida_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscalSaida_has_Produto` (
  `NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL`, `Produto_idProduto`),
  INDEX `fk_Nota Fiscal de Saída_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Nota Fiscal de Saída_has_Produto_Nota Fiscal de Saída1_idx` (`NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL` ASC) VISIBLE,
  CONSTRAINT `fk_Nota Fiscal de Saída_has_Produto_Nota Fiscal de Saída1`
    FOREIGN KEY (`NotaFiscalSaida_NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscalSaida` (`NotaFiscal_IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota Fiscal de Saída_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_NotaFiscalEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_NotaFiscalEntrada` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `NotaFiscalEntrada_NotaFiscal_IDNOTAFISCAL` INT UNSIGNED NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  `QUANTIDADE` DOUBLE NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `NotaFiscalEntrada_NotaFiscal_IDNOTAFISCAL`),
  INDEX `fk_Produto_has_Nota Fiscal de Entrada_Nota Fiscal de Entrad_idx` (`NotaFiscalEntrada_NotaFiscal_IDNOTAFISCAL` ASC) VISIBLE,
  INDEX `fk_Produto_has_Nota Fiscal de Entrada_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Nota Fiscal de Entrada_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Nota Fiscal de Entrada_Nota Fiscal de Entrada1`
    FOREIGN KEY (`NotaFiscalEntrada_NotaFiscal_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NotaFiscalEntrada` (`NotaFiscal_IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;